### ISSUE TITLE
VASLThread error

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1019]
Transferred from VASSAL#2514

VASL v6.6.1 3.5.8

java.lang.NullPointerException: Cannot invoke "VASL.LOS.Map.Map.onMap(int, int)" because "this.LOSMap" is null
 at VASL.build.module.map.VASLThread.setTargetFromRemoteEvent(VASLThread.java:482)
 at VASL.build.module.map.VASLThread.setEndPointsandLevels(VASLThread.java:1010)
 at VASL.build.module.map.VASLThread$VASLLOSCommand.executeCommand(VASLThread.java:1230)
 at VASSAL.command.Command.execute(Command.java:62)

**Comment by derimmer** [comment]
Added error handling
