### ISSUE TITLE
board exception with vassal 3.6.0b3

### ISSUE THREAD

**Issue by zgrose** [vasl-developers/vasl#1021]
Not sure why this happens yet, but some boards have this issue with VASSAL 3.6.0b3:

````
2021-10-15 00:25:50,890 [22676-main] INFO  VASSAL.launch.StartUp - Starting
2021-10-15 00:25:50,903 [22676-main] INFO  VASSAL.launch.StartUp - OS Windows 7 6.1 amd64
2021-10-15 00:25:50,903 [22676-main] INFO  VASSAL.launch.StartUp - Java version 17
2021-10-15 00:25:50,903 [22676-main] INFO  VASSAL.launch.StartUp - Java home C:\Program Files\VASSAL-3.6.0-beta3\jre
2021-10-15 00:25:50,903 [22676-main] INFO  VASSAL.launch.StartUp - VASSAL version 3.6.0-beta3
2021-10-15 00:25:50,903 [22676-main] INFO  VASSAL.launch.Launcher - Player
2021-10-15 00:25:53,893 [22676-AWT-EventQueue-0] WARN  VASSAL.i18n.BundleHelper - No Translation: Icon when pieces and draggable overlays are showing:
2021-10-15 00:25:53,893 [22676-AWT-EventQueue-0] WARN  VASSAL.i18n.BundleHelper - No Translation: Icon when only draggable overlays are showing:
2021-10-15 00:25:53,893 [22676-AWT-EventQueue-0] WARN  VASSAL.i18n.BundleHelper - No Translation: Icon when only map is showing:
2021-10-15 00:25:56,775 [22676-AWT-EventQueue-0] INFO  VASSAL.build.GameModule - VASL version 6.6.2
2021-10-15 00:25:56,793 [22676-AWT-EventQueue-0] WARN  VASSAL.build.GameModule - No more than one [MapCenterer] allowed in Main Map [Map Window]
2021-10-15 00:26:21,927 [22676-AWT-EventQueue-0] INFO  VASSAL.launch.TilingHandler - No images to tile.
2021-10-15 00:26:21,944 [22676-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: bd03.gif Error: Image not found. Turn on the Audit Trail preference to generate more details in the errorlog. 
2021-10-15 00:27:31,152 [22676-AWT-EventQueue-0] INFO  VASL.build.module.ASLMap - LOS disabled - unexpected error
2021-10-15 00:27:31,154 [22676-AWT-EventQueue-0] INFO  VASL.build.module.ASLMap - 
java.lang.NullPointerException: Cannot invoke "VASL.LOS.Map.Hex.getColumnNumber()" because "upperLeft" is null
	at VASL.LOS.Map.Map.insertMap(Map.java:4317)
	at VASL.build.module.ASLMap.buildVASLMap(ASLMap.java:367)
	at VASL.build.module.ASLMap.setBoards(ASLMap.java:185)
	at VASSAL.build.module.map.BoardPicker.setup(BoardPicker.java:460)
	at VASL.build.module.map.ASLBoardPicker.setup(ASLBoardPicker.java:202)
	at VASSAL.build.module.GameState.setup(GameState.java:396)
	at VASSAL.build.module.GameState$6.actionPerformed(GameState.java:198)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
````

**Comment by derimmer** [comment]
This has been fixed by the 6.6.3.1 patch which will carry forward into 6.6.4
