### ISSUE TITLE
NPE in VASL.build.module.ColorChanger

### ISSUE THREAD

**Issue by uckelman** [vasl-developers/vasl#1055]
See [this thread](https://forum.vassalengine.org/t/3-6-2-and-vasl-6-6-3-1-oba-flowchart-vmdx-error/73348) for a full stack trace.

```
2021-12-14 16:31:27,940 [4860-AWT-EventQueue-0] WARN  VASSAL.tools.logging.LoggedOutputStream - java.lang.NullPointerException: Cannot invoke "java.awt.Color.getRGB()" because "replacement" is null
2021-12-14 16:31:27,940 [4860-AWT-EventQueue-0] WARN  VASSAL.tools.logging.LoggedOutputStream - 	at VASL.build.module.ColorChanger.changeColor(ASLChatter.java:1991)
2021-12-14 16:31:27,941 [4860-AWT-EventQueue-0] WARN  VASSAL.tools.logging.LoggedOutputStream - 	at VASL.build.module.ASLChatter.RebuildColoredDiceFaces(ASLChatter.java:1536)
2021-12-14 16:31:27,941 [4860-AWT-EventQueue-0] WARN  VASSAL.tools.logging.LoggedOutputStream - 	at VASL.build.module.ASLChatter$15.propertyChange(ASLChatter.java:1805)
```

Additionally, ColorChanger ought to be in its own file.

**Comment by derimmer** [comment]
I have moved ColorChanger to its own file. This may make #1068 a bit clearer as well. 

I have handled the NPE by setting replacement to a default colour if it is null:

> if (replacement==null) {
>             replacement=Color.WHITE;
> }

Assume this is acceptable practice?
