### ISSUE TITLE
moving to vassal3.6.X - deprecated code

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1075]
I have updated to vasl to build with vassal3.6.x (currrently 3.6.3). It successfully built and ran. I have pushed the related changes to github.

The maven build process listed the following deprecated code which needs to be change before vasl6.6.4 is released

>[WARNING] /c:/Users/dougr_000/IdeaProjects/664beta2/src/VASL/build/module/map/VASLThread.java:[436,80] getLocalizedText() in VASSAL.tools.FormattedString has been deprecated
[WARNING] /c:/Users/dougr_000/IdeaProjects/664beta2/src/VASL/build/module/map/CounterDetailViewer.java:[252,42] getLocalizedText(VASSAL.build.module.properties.PropertySource) in VASSAL.tools.FormattedString has been deprecated
[WARNING] /c:/Users/dougr_000/IdeaProjects/664beta2/src/VASL/build/module/map/CounterDetailViewer.java:[290,36] getLocalizedText() in VASSAL.tools.FormattedString has been deprecated
[WARNING] /c:/Users/dougr_000/IdeaProjects/664beta2/src/VASL/build/module/map/CounterDetailViewer.java:[297,35] getLocalizedText(VASSAL.build.module.properties.PropertySource) in VASSAL.tools.FormattedString has been deprecated
[WARNING] /c:/Users/dougr_000/IdeaProjects/664beta2/src/VASL/build/module/map/DoubleBlindViewer.java:[405,32] getText() in VASSAL.tools.FormattedString has been deprecated<

**Comment by derimmer** [comment]
@uckelman I just ran a new maven build. All worked fine; same 5 warnings about deprecated code. All point to VASSAL.tools.FormattedString. 

It appears that I need to swap out the calls to getLocalizedText() and getText(). There appear to be other versions of those methods that are not deprecated; they require parameters. I would need to set those parameters in the vasl code but I don't know where to get the values from? Where should I be looking and what should I be looking for? Many thanks.

**Comment by uckelman** [comment]
@BrentEaston What does the `Auditable` parameter for these need to be?

**Comment by derimmer** [comment]
@uckelman 

I have now moved the VASL build to VASSAL3.6.5 and would like to release a beta version of VASL6.6.4 in the next couple of weeks.

Maven is still reporting the same 5 warnings about deprecated code. I have not heard from Brent so still not sure how to resolve them.

**Comment by BrentEaston** [comment]
Sorry guys, missed this one.

All AbstractBuildables and AbstractConfigurables implement Auditable, so usually you can just supply 'this' as the Auditable parameter when working on a component. In the worst case, you can just supply a null or  ((Auditable) null) as the Auditable parameter,

**Comment by derimmer** [comment]
Thanks for the help. I proceeded accordingly, using this and (String) null for the params in CounterDetailViewer; and null in VASLThread. I changed the code in DoubleBlindViewer such that the getLocalizedText() method is no longer needed (DBV is not active in our code at present in any event). 

The code built fine with maven and showed no deprecated methods. However, when i ran it in my dev environment and used CounterDetailViewer (which shows a popup window of hex contents when hovering over a stack) I got the following error:

> 2022-02-24 17:59:35,569 [38192-main] INFO  VASSAL.launch.StartUp - Starting
2022-02-24 17:59:35,602 [38192-main] INFO  VASSAL.launch.StartUp - OS Windows 10 10.0 amd64
2022-02-24 17:59:35,602 [38192-main] INFO  VASSAL.launch.StartUp - Java version 11.0.7
2022-02-24 17:59:35,602 [38192-main] INFO  VASSAL.launch.StartUp - Java home C:\Program Files\Java\jdk-11.0.7
2022-02-24 17:59:35,603 [38192-main] INFO  VASSAL.launch.StartUp - VASSAL version 3.6.5
2022-02-24 17:59:35,603 [38192-main] INFO  VASSAL.launch.Launcher - Player
2022-02-24 17:59:40,429 [38192-AWT-EventQueue-0] WARN  VASSAL.i18n.BundleHelper - No Translation: Icon when pieces and draggable overlays are showing:
2022-02-24 17:59:40,430 [38192-AWT-EventQueue-0] WARN  VASSAL.i18n.BundleHelper - No Translation: Icon when only draggable overlays are showing:
2022-02-24 17:59:40,430 [38192-AWT-EventQueue-0] WARN  VASSAL.i18n.BundleHelper - No Translation: Icon when only map is showing:
2022-02-24 17:59:42,861 [38192-AWT-EventQueue-0] INFO  VASSAL.build.GameModule - VASL version 6.6.4-beta5
2022-02-24 17:59:43,158 [38192-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Loading extension C:\Users\dougr_000\Documents\Programming Documents\VASLBuilds\ext\Aircraft52.mdx
2022-02-24 17:59:43,200 [38192-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Extension Aircraft52 v5.0 loaded
2022-02-24 17:59:43,200 [38192-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Loading extension C:\Users\dougr_000\Documents\Programming Documents\VASLBuilds\ext\BFPv5.01.vmdx
2022-02-24 17:59:43,441 [38192-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Extension BFPv5.01 v5.01 loaded
2022-02-24 17:59:43,441 [38192-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Loading extension C:\Users\dougr_000\Documents\Programming Documents\VASLBuilds\ext\hideable-control-markers-1.8.vmdx
2022-02-24 17:59:43,472 [38192-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Extension hideable-control-markers-1.8 v1.8 loaded
2022-02-24 17:59:43,473 [38192-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Loading extension C:\Users\dougr_000\Documents\Programming Documents\VASLBuilds\ext\neals-vasl-charts-v1-0.vmdx
2022-02-24 17:59:43,478 [38192-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Extension neals-vasl-charts-v1-0 v0.0 loaded
2022-02-24 17:59:43,479 [38192-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Loading extension C:\Users\dougr_000\Documents\Programming Documents\VASLBuilds\ext\oba-flowchart.vmdx
2022-02-24 17:59:43,490 [38192-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Extension oba-flowchart v1.1 loaded
2022-02-24 17:59:43,490 [38192-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Loading extension C:\Users\dougr_000\Documents\Programming Documents\VASLBuilds\ext\PTOTerrain.vmdx
2022-02-24 17:59:43,495 [38192-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Extension PTOTerrain v0.0 loaded
2022-02-24 17:59:43,495 [38192-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Loading extension C:\Users\dougr_000\Documents\Programming Documents\VASLBuilds\ext\RSCh.vmdx
2022-02-24 17:59:43,513 [38192-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Extension RSCh v1.0 loaded
2022-02-24 17:59:43,514 [38192-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Loading extension C:\Users\dougr_000\Documents\Programming Documents\VASLBuilds\ext\secret-dr-1.0.vmdx
2022-02-24 17:59:43,523 [38192-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Extension secret-dr-1.0 v1.0 loaded
2022-02-24 17:59:43,523 [38192-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Loading extension C:\Users\dougr_000\Documents\Programming Documents\VASLBuilds\ext\terrain-chart-1.2.1.vmdx
2022-02-24 17:59:43,528 [38192-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Extension terrain-chart-1.2.1 v1.2.1 loaded
2022-02-24 17:59:43,528 [38192-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Loading extension C:\Users\dougr_000\Documents\Programming Documents\VASLBuilds\ext\VASLOverlays_v2.10.vmdx
2022-02-24 17:59:43,647 [38192-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Extension VASLOverlays_v2.10 v2.1 loaded
2022-02-24 18:00:02,150 [38192-AWT-EventQueue-0] INFO  VASSAL.launch.TilingHandler - No images to tile.
2022-02-24 18:01:01,094 [38192-AWT-EventQueue-0] ERROR VASSAL.tools.ErrorDialog - 
java.lang.NullPointerException: null
	at VASSAL.i18n.Resources.getBundleForKey(Resources.java:298)
	at VASSAL.i18n.Resources.getInstanceString(Resources.java:294)
	at VASSAL.i18n.Resources.getString(Resources.java:277)
	at VASSAL.tools.FormattedString.getLocalizedText(FormattedString.java:287)
	at VASL.build.module.map.CounterDetailViewer.drawText(CounterDetailViewer.java:297)
	at VASSAL.build.module.map.CounterDetailViewer.draw(CounterDetailViewer.java:303)
	at VASSAL.build.module.map.CounterDetailViewer.draw(CounterDetailViewer.java:273)
	at VASSAL.build.module.Map.drawDrawable(Map.java:2314)
	at VASSAL.build.module.Map.paintRegion(Map.java:2197)
	at VASSAL.build.module.Map.paintRegion(Map.java:2183)
	at VASSAL.build.module.Map$View.paint(Map.java:3822)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1643)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1618)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1556)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1890)
	at java.desktop/java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:313)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
>

Any thoughts?

**Comment by BrentEaston** [comment]
You can use null for the String parameter, only the Autidable parameter

**Comment by uckelman** [comment]
You mustn't pass `null` to `FormatttedString.getLocalizedText() as the `key` argument.

**Comment by BrentEaston** [comment]
I'm guessing you don't have a translation key set up for the string in question. Try passing "" instead of null withing custom code.  This may generate a 'No Translation: " warning but you can ignore it.

**Comment by derimmer** [comment]
@uckelman @BrentEaston Passing "" did the trick. Thanks.
