### ISSUE TITLE
Possible crash in 6.6.5-beta3 

### ISSUE THREAD

**Issue by pacman-ghost** [vasl-developers/vasl#1223]
I was testing VASL 6.6.5-beta3 with vasl-templates, and while everything seems to work, it sometimes crashes:

```
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "colorname" is null
        at VASL.build.module.map.DiceRollQueueHandler.getDieColor(ASLDiceOverlay.java:618)
        at VASL.build.module.map.DiceRollQueueHandler.RebuildSingleDieFaces(ASLDiceOverlay.java:663)
        at VASL.build.module.map.DiceRollQueueHandler.lambda$SetupPreferences$8(ASLDiceOverlay.java:476)
        at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
        at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335)
        at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
        at VASSAL.configure.Configurer.fireUpdate(Configurer.java:135)
        at VASL.build.module.map.DiceRollQueueHandler.SetupPreferences(ASLDiceOverlay.java:480)
        at VASL.build.module.map.ASLDiceOverlay.addTo(ASLDiceOverlay.java:970)
        at VASSAL.build.Builder.build(Builder.java:82)
        at VASSAL.build.AbstractBuildable.build(AbstractBuildable.java:104)
        at VASSAL.build.module.Map.build(Map.java:696)
        at VASSAL.build.Builder.create(Builder.java:126)
        at VASSAL.build.Builder.build(Builder.java:80)
        at VASSAL.build.AbstractBuildable.build(AbstractBuildable.java:104)
        at VASSAL.build.GameModule.build(GameModule.java:692)
        at VASSAL.build.GameModule.build(GameModule.java:624)
        at VASSAL.build.GameModule.init(GameModule.java:1852)
        at vassal_shim.VassalShim.<init>(VassalShim.java:123)
        at vassal_shim.Main.main(Main.java:69)
```

It's not a big deal - this kind of thing is not unusual, since I'm using VASSAL+VASL in a way that it was never designed to be used, and it's not uncommon for the GUI to crash, while the stuff I'm doing (e.g. updating a .vsav) works - but it could be indicative of a problem.

**Comment by derimmer** [comment]
Thanks for this. I had not found this bug yet. It has to do with converting the chat window to html. That meant redoing the way dice images are generated. I thought I had trapped all the null possibilities for "colorname" but looks like I missed one (at least).  

I should be able to fix this for the official release.

**Comment by pacman-ghost** [comment]
No worries. If you send me an interim build, I can run it through my test suite again, and make sure there aren't any other issues.

**Comment by derimmer** [comment]
Here is a link to a new interim build which I hope will prevent the crash. Thanks for testing it!

https://www.dropbox.com/s/7otv7uac2d7fv41/vasl-6.6.5-beta5.vmod?dl=0
