### ISSUE TITLE
standard overlay G5 throwing exceptions if terrain SSR is Grain -> Rice Paddies

### ISSUE THREAD

**Issue by zgrose** [vasl-developers/vasl#1546]
Steps to repro:
Start a new VASL game. Pick board 57. Set Grain to Rice Paddies. Add overlay G5 to M5, M6

Reversing the order (add overlay, then set grain to rice paddies) also fails.

<img width="776" alt="Screenshot 2023-09-27 124836" src="https://github.com/vasl-developers/vasl/assets/5044847/4a3c35bb-7075-4bc6-bf0d-0d357d62c571">

<img width="562" alt="Screenshot 2023-09-27 124852" src="https://github.com/vasl-developers/vasl/assets/5044847/79e62572-7a51-45ad-a551-724eb120d9a6">

````
2023-09-27 12:49:47,478 [4336-AWT-EventQueue-0] ERROR VASSAL.tools.ErrorDialog - 
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "VASL.build.module.map.boardPicker.Overlay.bounds()" because "this.overlay" is null
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
	at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
	at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:848)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:858)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1080)
	at java.desktop/java.awt.Component.show(Component.java:1728)
	at java.desktop/java.awt.Component.setVisible(Component.java:1675)
	at java.desktop/java.awt.Window.setVisible(Window.java:1036)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1016)
	at VASL.build.module.map.ASLBoardPicker.actionPerformed(ASLBoardPicker.java:837)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6620)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6385)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4995)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1080)
	at java.desktop/java.awt.Component.show(Component.java:1728)
	at java.desktop/java.awt.Component.setVisible(Component.java:1675)
	at java.desktop/java.awt.Window.setVisible(Window.java:1036)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1016)
	at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.showInDialog(WizardDisplayerImpl.java:363)
	at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.show(WizardDisplayerImpl.java:268)
	at org.netbeans.api.wizard.WizardDisplayer.showWizard(WizardDisplayer.java:107)
	at VASSAL.build.module.WizardSupport.showWelcomeWizard(WizardSupport.java:166)
	at VASSAL.launch.Player.showWizardOrPlayerWindow(Player.java:128)
	at VASSAL.launch.Player.launch(Player.java:97)
	at VASSAL.launch.Launcher$1.run(Launcher.java:98)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "VASL.build.module.map.boardPicker.Overlay.bounds()" because "this.overlay" is null
	at VASSAL.tools.opcache.OpCache.getFuture(OpCache.java:323)
	at VASSAL.tools.opcache.OpCache.get(OpCache.java:261)
	at VASSAL.tools.opcache.AbstractOpImpl.get(AbstractOpImpl.java:80)
	at VASSAL.tools.imageop.AbstractOpImpl.getImage(AbstractOpImpl.java:101)
	at VASSAL.tools.imageop.AbstractTiledOpImpl.getTile(AbstractTiledOpImpl.java:137)
	at VASSAL.tools.imageop.AbstractOpImpl.getTile(AbstractOpImpl.java:176)
	at VASSAL.build.module.map.boardPicker.board.GridOp.draw(GridOp.java:104)
	at VASSAL.build.module.map.boardPicker.board.GridOp$TileOp.eval(GridOp.java:187)
	at VASSAL.build.module.map.boardPicker.board.GridOp$TileOp.eval(GridOp.java:138)
	at VASSAL.tools.opcache.OpCache$Request.doInBackground(OpCache.java:203)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "VASL.build.module.map.boardPicker.Overlay.bounds()" because "this.overlay" is null
	at VASSAL.tools.opcache.OpCache.getFuture(OpCache.java:323)
	at VASSAL.tools.opcache.OpCache.get(OpCache.java:261)
	at VASSAL.tools.opcache.AbstractOpImpl.get(AbstractOpImpl.java:80)
	at VASSAL.tools.imageop.AbstractOpImpl.getImage(AbstractOpImpl.java:101)
	at VASSAL.tools.imageop.ScaleOpBitmapImpl$TileOp.eval(ScaleOpBitmapImpl.java:180)
	at VASSAL.tools.imageop.ScaleOpBitmapImpl$TileOp.eval(ScaleOpBitmapImpl.java:125)
	at VASSAL.tools.opcache.OpCache.getFuture(OpCache.java:318)
	... 15 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "VASL.build.module.map.boardPicker.Overlay.bounds()" because "this.overlay" is null
	at VASL.build.module.map.boardPicker.Underlay.loadImage(Underlay.java:112)
	at VASL.build.module.map.boardPicker.Overlay.getImage(Overlay.java:140)
	at VASL.build.module.map.boardPicker.ASLBoard$BoardOp.eval(ASLBoard.java:416)
	at VASL.build.module.map.boardPicker.ASLBoard$BoardOp.eval(ASLBoard.java:343)
	at VASSAL.tools.opcache.OpCache.getFuture(OpCache.java:318)
	... 21 common frames omitted
````

**Comment by derimmer** [comment]
Thanks Zoltan. I didn’t see a vasl version in the error log but maybe I missed it. If it is 666 or less then it is the known overlay bug and should be fixed in 667. If it occurred with one of the 667beta then shit!

**Comment by zgrose** [comment]
I'll grab a beta and check...

**Comment by zgrose** [comment]
in 6.6.7-beta5, the exception isn't thrown. of course, one doesn't get rice paddy graphics either, but that seems like a different problem. :)

**Comment by derimmer** [comment]
Thanks Zoltan. I am going to close this issue because it is covered by #1406. The terrain transformation issue is as you note a separate and distinct issue.
