### ISSUE TITLE
Bug and improvement suggestions

### ISSUE THREAD

**Issue by geezer09** [vasl-developers/vasl#1899]
I would like to open up the suggestions for improving VASL to the numerous players that do not participate to the online forums or this github issue tracker. As far as I know those are the only two ways for players to make suggestions. Although functional, I think we are missing out on the numerous ideas for improvements from players that don’t want to use the existing methods. 

What I would like to see is a prompt everytime a game is loaded encouraging users to make suggestions or report bugs and then add a menu item that opens up a window for the player to type in his recommendation and enter his email if he wishes.

This would then automatically generate an issue on this github repo. 

@derimmer has been doing tremendous work in trying to consolidate and update the issues on this page but this is not sustainable in my opinion.

**Comment by derimmer** [comment]
When you implement this, I think it might be a good idea to force the identification of a bug or suggestion. This would allow us to easily identify a list of one or the other.

**Comment by geezer09** [comment]
Hey @derimmer, this is ready to be incorporated for the next beta. The only thing is I need to create a Fine-grained personal access token in order for the API to connect to github and create the issue. I was using my own account for testing but I am not able to create a fine-grained PAT for some reason, probably because I am not the repo administrator. 

Do you want to create the token and limit the right to only allow read and write access to issues in the vasl repo?

**Comment by derimmer** [comment]
Happy to do so but I have absolutely no idea what a fine-grained PAT is or how to go about creating one. 

Can you point me to instructions?

**Comment by zgrose** [comment]
Are you sure you want a PAT over a GitHub App?

**Comment by geezer09** [comment]
GitHub app is the proper way but also a bit more work. We can transition to that down the road if necessary. One solution would be to create a bot account and use it’s token. The one issue with @derimmer using his token is that any issues created  by players will appear under his name. If that annoys you, you should create a bot account.

Github has a wealth of good info on how to create these tokens, nothing too complicated.

**Comment by derimmer** [comment]
It appears that I have to set some "policies" for the orgization before I can create the fine-grained PAT.

I chose to Allow Access via fine-grained PAT and require Admin Approval.

I chose to Restrict Access via PAT (Classic). 

It also seems like the lifespan of the PATs will be 366 days. 

I am pretty sure I can change all of the above at any time should we need to do so. 

Do you now need me to create a PAT in my own name? I guess I would have to send a request to myself.

**Comment by derimmer** [comment]
It appears that I can grant a PAT to anyone who requests one.

**Comment by geezer09** [comment]
So I think we have three options

1) You can create a fine grained token that will ONLY allow to create github issues to the repo, I will then hardcode that token into the code. Anybody that wants to, will be able to see and steal this token if they feel inclined. As long as you create the token properly, only minimal damage could be done with this token. 

2) You look up how to create a github app so that my code can dynamically generate a token every time a user submits the form from within VASL.

3) You can grant me admin status so I can do it myself.

Option 1 is the easiest but the least safe. Option 2 is what I would prefer if your up for it.

**Comment by derimmer** [comment]
Option 2 it is.

________________________________

**Comment by derimmer** [comment]
I am trying to Register the App (which is step 1 in creating it).

I am immediately asked for a Homepage URL and a Callback URL. 

It is not clear to me how I would generate those nor what they should be. Any ideas?

**Comment by geezer09** [comment]
Honestly, I have never created a github app so the only help I can provide is to guide you towards https://docs.github.com/en/apps/creating-github-apps/about-creating-github-apps/about-creating-github-apps 
or your genAI friend who will gladly guide you through the steps.

**Comment by derimmer** [comment]
I believe I have created a Github App at https://github.com/settings/apps. It is called Submit An Issue. I had to make a bunch of choices, which I did. I pressume we can change anything that needs changing. 

Of course, what I created was just a shell and now needs someone (you I presume), to add actual functionality to it. 

I suspect I will have to give you permission to edit it. Let me know if that is what happens.

**Comment by geezer09** [comment]
The next step will be to create a github action secret so I can access the github app within the code.

https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions

**Comment by derimmer** [comment]
Should be able to work on this a little later today

**Comment by derimmer** [comment]
I believe that I have created the secret at the level of the vasl repository.

It is named issuesec1.

I will check to see if I can/have to give you access to it.

________________________________

**Comment by geezer09** [comment]
Hey Doug, I am currently working on this and it seems like you have properly configured the secret.

Can you email it to me so I can do some local testing. As of right now the only way of testing is to create new releases to extract the token 

larochellejo@hotmail.com

**Comment by derimmer** [comment]
I cannot seem to find a file to email to you. I can see the secret I created in github (it is blank; I just created a shell with name issuesec1) but I can't see how I can send it to you. 

I have just granted you Admin Access for all our repositories.

**Comment by derimmer** [comment]
Github just sent me a request to approve vasl issues. I believe I have done so but Github is so obscure I can't be sure. Let me know if there is a problem.

**Comment by geezer09** [comment]
Yeah it seems to be working.

**Comment by derimmer** [comment]
In order to do a test build of 6.7.0 including your HIP bug fix, I pulled all of the recent changes to develop into my branch on github (issue#1320). After that PR my github branch showed itself as one commit ahead of develop (which is the PR itself). I then pulled all of the changes from my github branch into my local branch on my local device. This included GitHubIssueCreator.java and related stuff.

I built the module locally using maven and ran it successfully in my IDE (yeah, that did not happen first time. I had to add bunch of new dependencies to my project before it would run under the IDE). Those dependences were

![Image](https://github.com/user-attachments/assets/6f9c639f-59df-42ee-9a5f-fd585c9746ea)

The first six were necessary to make the following import statements in GitHubIssueCreator.java stop showing package not found errors. The final one was necessary to fix an issue with okhttp3. I googled the error message I was getting and implemented the fix suggested.

>
>import com.auth0.jwt.JWT;
>import com.auth0.jwt.algorithms.Algorithm;

>import okhttp3.*;
>import org.json.JSONArray;
>import org.json.JSONObject;
>
While running the project in my IDE, I found the Submit A Suggestion option and opened it but did not submit an item. Excellent!

However, I then tried to take the .vmod produced by Maven and run it from the VASSAL window just as users would do. When I did that I got an Bug Report:

2025-03-28 22:36:26,136 [11304-AWT-EventQueue-0] INFO  VASSAL.build.GameModule - Exiting
2025-03-28 22:36:32,111 [27624-SwingWorker-pool-2-thread-2] INFO  VASSAL.launch.AbstractLaunchAction - Loading module file C:\Users\DougR\Ideaprojects\issue1320\target\vasl-6.7.0.vmod
2025-03-28 22:36:32,666 [27624-SwingWorker-pool-2-thread-2] INFO  VASSAL.launch.TilingHandler - No images to tile.
2025-03-28 22:36:32,670 [27624-SwingWorker-pool-2-thread-2] INFO  VASSAL.launch.AbstractLaunchAction - Loading module VASL
2025-03-28 22:36:32,671 [27624-SwingWorker-pool-2-thread-2] INFO  VASSAL.tools.io.ProcessLauncher - launching C:\Program Files\VASSAL-3.7.15\jre\bin\java -Xms1024M -Xmx1024M -Duser.home=C:\Users\DougR -Duser.dir=C:\Program Files\VASSAL-3.7.15 -cp lib\Vengine.jar VASSAL.launch.Player --load -- C:\Users\DougR\Ideaprojects\issue1320\target\vasl-6.7.0.vmod
2025-03-28 22:36:33,173 [23276-main] INFO  VASSAL.launch.StartUp - Starting
2025-03-28 22:36:33,180 [23276-main] INFO  VASSAL.launch.StartUp - OS Windows 11 10.0 amd64
2025-03-28 22:36:33,181 [23276-main] INFO  VASSAL.launch.StartUp - Java version 23.0.1
2025-03-28 22:36:33,181 [23276-main] INFO  VASSAL.launch.StartUp - Java home C:\Program Files\VASSAL-3.7.15\jre
2025-03-28 22:36:33,181 [23276-main] INFO  VASSAL.launch.StartUp - VASSAL version 3.7.15
2025-03-28 22:36:33,181 [23276-main] INFO  VASSAL.launch.Launcher - Player
2025-03-28 22:36:35,325 [23276-AWT-EventQueue-0] ERROR VASSAL.tools.ErrorDialog - 
VASSAL.build.IllegalBuildException: failed to load class VASL.build.module.GitHubIssueCreator
	at VASSAL.build.Builder.create(Builder.java:148)
	at VASSAL.build.Builder.build(Builder.java:80)
	at VASSAL.build.AbstractBuildable.build(AbstractBuildable.java:104)
	at VASSAL.build.module.Documentation.build(Documentation.java:75)
	at VASSAL.build.Builder.create(Builder.java:130)
	at VASSAL.build.Builder.build(Builder.java:80)
	at VASSAL.build.AbstractBuildable.build(AbstractBuildable.java:104)
	at VASSAL.build.GameModule.build(GameModule.java:788)
	at VASSAL.build.GameModule.build(GameModule.java:719)
	at VASSAL.build.GameModule.init(GameModule.java:1992)
	at VASSAL.launch.Player.launch(Player.java:86)
	at VASSAL.launch.Launcher$1.run(Launcher.java:96)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3621)
	at java.base/java.lang.Class.getConstructor0(Class.java:3826)
	at java.base/java.lang.Class.getConstructor(Class.java:2501)
	at VASSAL.build.Builder.create(Builder.java:118)
	... 24 common frames omitted
Caused by: java.lang.ClassNotFoundException: Unable to load class org.bouncycastle.jce.provider.BouncyCastleProvider
	at VASSAL.tools.DataArchive.findClass(DataArchive.java:463)
	at VASSAL.tools.DataArchive.loadClass(DataArchive.java:436)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528)
	... 29 common frames omitted
Caused by: java.io.FileNotFoundException: 'org/bouncycastle/jce/provider/BouncyCastleProvider.class' not found in C:\Users\DougR\Ideaprojects\issue1320\target\vasl-6.7.0.vmod
	at VASSAL.tools.DataArchive.getInputStream(DataArchive.java:179)
	at VASSAL.tools.DataArchive.findClass(DataArchive.java:459)
	... 31 common frames omitted

I am concerned that the workflow will also successfully build the module but that we may get the same error when running under VASSAL. Have you tried that at your end? Any suggestions?

**Comment by geezer09** [comment]
Those dependencies are required for the issue creator module, just keep that one  or two commits out of the build and you will probably avoid all those problems. I brought up the idea of trying to keep a nice commit history and this a perfect example of why. I think all my code related to the issue creator was in one or two commits, you should be able to locate those and exclude them from the production

**Comment by derimmer** [comment]
> you should be able to locate those and exclude them from the production

I am not proficient in GitHub so I have not the slightest idea how to do this. I spent some time with Google and it seemed that (a) .github does not allow files from a commit to be excluded from a PR. There were some workarounds which required using various commands at the Git command line, which I am not comfortable doing for fear of screwing something up bigtime. 

Instead, I removed the GitHubIssueCreator reference from the buildFile. Maven is able to build and the .vmod works from the VASSAL window. This should work for the workflow build process? We can of course, add the reference back in as soon as 6.7.0 is released.

**Comment by derimmer** [comment]
@geezer09 I have had a report which I have tested and can confirm that the issue creator is not working as of 6.7.1-beta5. It always returns "Submission Failed". 

I did a little bit of tracking in my dev environment and it seems that the problem arises at line 261 in GitHubIssueCreator.submitGitHubIssue():

String jwt = generateJwt();

jwt always comes back null and that trips the Submission Failed.

**Comment by joseph-larochelle** [comment]
Yeah i need to address that, its a token issue. Ill try to fix it today or tomorrow

**Comment by derimmer** [comment]
Super. I will wait on issuing beta6 until you get a chance to fix it as it would be a perfect and important way for people to give feedback on the cropping and flipping testing. Good way to get the feeback but also a good way to hightlight the suggestion/bug report tool, which I think is a great addition. I plan to highlight it's availability in my posts about beta6.

**Comment by joseph-larochelle** [comment]
Ok please be patient with me on this on I am super swamped right now, i might not get to it until later this week.

**Comment by derimmer** [comment]
No rush at all. I will certainly wait as it will really help with what I am trying to do with beta6. But nobody needs to see beta6 right away. Get to it when you can. Cheers!

**Comment by derimmer** [comment]
@joseph-larochelle @zgrose 

I am happy to take on this issue and get the suggestion feature working again. I think it would be a really helpful tool and might bring some order to the suggestion/bug reporting chaos that we have at present. 

In Joseph's July 29, 2025 message he indicated that it was a token issue. Does that make it something that we fix within GitHub? I have all the necessary rights and privileges to do so and none of the knowledge of how to do so. If someone can point me in the right direction, I will give it a go.

**Comment by geezer09** [comment]
Hey Doug, yeah sure go ahead. What you need to do is create a token from your github account that has the required permissions (write issues) and then paste it in the code file that probably has a name like github- issue-creator.

Just make sure you create a token with the minimal permissions required

**Comment by derimmer** [comment]
From a review of the GitHubIssueCreator class and various helpfiles in github, I am assuming that I am looking to create an "installation access token" as opposed to a "personal access token" or a "user access token". 

Am I right?

If so, I have the instructions from github and will attempt to follow. 

Thanks. 

----------

EDIT: After more reading, I conclude that the above is wrong. 

When I run the GitHubIssueCreator code it exits at the following line of code in method generatJWT()

if (GITHUB_PRIVATE_KEY == null || GITHUB_PRIVATE_KEY.isEmpty()) {
            //logErrorToChat("Error: GitHub private key is not set. Please ensure the GITHUB_PRIVATE_KEY environment variable is configured.");
            return null;
        }

It will always return null since it is not given any value in VASL as far as I can tell.

So, am a trying to create a token that I can then assign to GITHUB_PRIVATE_KEY?

**Comment by derimmer** [comment]
ON GitHub, under Developer Settings, I found the Submit An Issue app and added a client secret. I pasted first my Github private key and then the client secret into GitHubIssueCreator. Neither would work when passed to method loadPrivateKey().

**Comment by derimmer** [comment]
Github documentation is too technical for my knowledge base. Switching to Google. 

Partial success; which I am documenting for future reference. 

The GitHub App ID and GitHub Client ID shown on GitHub for the Submit An Issue App no longer match the values set in the GitHubIssueCreator class in VASL. I updated the values in VASL to match those in GitHub. 

(Issue: how did these values change and will we need to keep updating them in the future?)

Rather than copy the GitHub Private Key value into VASL as a string, I added the .PEM file to VASL in the dist folder and then read it as string from within the GitHubIssueCreator class:

GITHUB_PRIVATE_KEY = new String(Files.readAllBytes(Paths.get("dist/Filename for the  private key.pem in dist")

When using these new values GitHubIssueCreator.loadPrivateKey() worked and the code moved into the getInstallationID() method. At present, this method fails.

**Comment by uckelman** [comment]
> Rather than copy the GitHub Private Key value into VASL as a string, I added the .PEM file to VASL in the dist folder and then read it as string from within the GitHubIssueCreator class

Now you need to change the private key, because you've made it public.

You absolutely MUST NOT embed a private key in the software you distribute.

**Comment by derimmer** [comment]
Well, I only did this in my local dev environment but I will nonetheless generate a new private key and will not include it in VASL. 

Are you aware of any VASSAL module that allows the user to write to github (which is what I think we are trying to do here)? I will continue to work away on this on my own (tough sledding I have to admit) but would be delighted to steal, I mean copy, someone else's good work.

**Comment by uckelman** [comment]
> Are you aware of any VASSAL module that allows the user to write to github (which is what I think we are trying to do here)? 

I know of no modules which do this, but Vassal does this itself for collecting exception reports. The client code is in `VASSAL.tools.BugUtils`. The server code is in `/util/abr` in the site repo.

https://github.com/vassalengine/vassal/blob/master/vassal-app/src/main/java/VASSAL/tools/BugUtils.java

https://github.com/vassalengine/vassal-site/tree/main/util/abr

The code on the server side is Python using the Flask framework, which work, but neither of which I'd use for something new at this point. (The next time I need to do something like this I will use Rust and Axum.)

**Comment by derimmer** [comment]
@uckelman thanks for your comments above.  I looked at both the links you gave. It seemed to come at the problem in different way than Joseph's class and I am reluctant to do a full-scale rewrite. 

I have spent considerable time looking at @joseph-larochelle 's code in GitHubIssieCreator and reading the GitHub documentation on Private Keys, Secrets and Variables. 

I must concede that I do not have the knowledge nor the learning capacity to climb this hill. There is simply too much that I do not understand. 

I can generate private keys and secrets in GitHub but I cannot figure out how to give access to them in a secure fashion to VASL users.

I have deleted the reference to GitHubIssueCreator in the buildFile so the menu item Submit Suggestion will not longer appear on the Help menu in 672b3 forward. 

This is still a great idea and if somebody can figure out how to make the connection between GitHub and VASSAL instances, that would be great.

**Comment by uckelman** [comment]
> I have spent considerable time looking at @joseph-larochelle 's code in GitHubIssieCreator 

Where is this?

**Comment by derimmer** [comment]
GitHubIssueCreator is a class in VASL.buiild.module.

**Comment by uckelman** [comment]
I've looked at it now. That approach can't keep your private key private if the code is running on the user's system, because the code requires the private key.
