### ISSUE TITLE
NPE in LOS for SSR terrain change

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#241]
2015-10-20 19:56:27,799 [1-AWT-EventQueue-0] INFO  VASL.build.module.ASLMap - LOS disabled - unexpected error
2015-10-20 19:56:27,977 [1-AWT-EventQueue-0] INFO  VASL.build.module.ASLMap - 
java.lang.NullPointerException: null
    at VASL.LOS.Map.Hex.resetTerrain(Hex.java:589) ~[na:na]
    at VASL.LOS.Map.Map.resetHexTerrain(Map.java:288) ~[na:na]
    at VASL.build.module.map.boardPicker.VASLBoard.applyColorSSRules(VASLBoard.java:386) ~[na:na]
    at VASL.build.module.ASLMap.buildVASLMap(ASLMap.java:289) [na:na]
    at VASL.build.module.ASLMap.setBoards(ASLMap.java:162) [na:na]
    at VASSAL.build.module.map.BoardPicker$SetBoards.executeCommand(BoardPicker.java:756) [Vengine.jar:na]

File: J122 - Bloody Bois Jacques - German setup.vsav

To recreate: 
- Pick new boards
- Terrain SSR changes
- Set month to December

**Comment by davidsullivan317** [comment]
Tested with beta1 and is no longer occurring.
