### ISSUE TITLE
Dragging a counter off a QC menu throws NPE

### ISSUE THREAD

**Issue by zgrose** [vasl-developers/vasl#251]
VASSAL 3.2.15
VASL 6.3
Start new game offline
Pick board 01
Finish

Pull a Melee counter from the CC quick counter bar.

2015-11-17 22:50:17,614 [0-main] INFO  VASSAL.launch.StartUp - Starting
2015-11-17 22:50:17,616 [0-main] INFO  VASSAL.launch.StartUp - OS Mac OS X 10.11.1
2015-11-17 22:50:17,616 [0-main] INFO  VASSAL.launch.StartUp - Java version 1.8.0_66
2015-11-17 22:50:17,616 [0-main] INFO  VASSAL.launch.StartUp - VASSAL version 3.2.15
2015-11-17 22:50:17,816 [0-AWT-EventQueue-0] INFO  VASSAL.launch.ModuleManager - Manager
2015-11-17 22:50:20,994 [0-SwingWorker-pool-714192875-thread-1] INFO  VASSAL.launch.AbstractLaunchAction - Loading module file /Users/zgrose/Dropbox/VASSAL/VASL/vasl-6.3.0.vmod
2015-11-17 22:50:21,523 [0-SwingWorker-pool-714192875-thread-1] INFO  VASSAL.launch.TilingHandler - No images to tile.
2015-11-17 22:50:21,524 [0-SwingWorker-pool-714192875-thread-1] INFO  VASSAL.launch.AbstractLaunchAction - Loading module VASL
2015-11-17 22:50:21,529 [0-SwingWorker-pool-714192875-thread-1] INFO  VASSAL.tools.io.ProcessLauncher - launching /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -Xms512M -Xmx1024M -DVASSAL.id=1 -DVASSAL.port=64797 -Duser.home=/Users/zgrose -Duser.dir=/Applications/VASSAL.app -cp Contents/Resources/Java/Vengine.jar -Xdock:name=VASL -Xdock:icon=/Applications/VASSAL.app/Contents/Resources/VASSAL.icns -Dapple.awt.graphics.UseQuartz=false VASSAL.launch.Player --load -- /Users/zgrose/Dropbox/VASSAL/VASL/vasl-6.3.0.vmod
2015-11-17 22:50:21,965 [1-main] INFO  VASSAL.launch.StartUp - Starting
2015-11-17 22:50:21,972 [1-main] INFO  VASSAL.launch.StartUp - OS Mac OS X 10.11.1
2015-11-17 22:50:21,972 [1-main] INFO  VASSAL.launch.StartUp - Java version 1.8.0_66
2015-11-17 22:50:21,972 [1-main] INFO  VASSAL.launch.StartUp - VASSAL version 3.2.15
2015-11-17 22:50:21,972 [1-main] INFO  VASSAL.launch.Launcher - Player
2015-11-17 22:50:23,450 [1-IconFactory-preload] INFO  VASSAL.tools.icon.IconFactory - VASSAL images folder found at jar:file:/Applications/VASSAL.app/Contents/Resources/Java/Vengine.jar!/images/
2015-11-17 22:50:23,453 [1-IconFactory-preload] INFO  VASSAL.tools.icon.IconFactory - Icon family network-server created for network-server.png
2015-11-17 22:50:23,453 [1-IconFactory-preload] INFO  VASSAL.tools.icon.IconFactory - Icon family go-down created for go-down.png
2015-11-17 22:50:23,453 [1-IconFactory-preload] INFO  VASSAL.tools.icon.IconFactory - Icon family network-idle created for network-idle.png
2015-11-17 22:50:23,453 [1-IconFactory-preload] INFO  VASSAL.tools.icon.IconFactory - Icon family VASSAL created for VASSAL.png
2015-11-17 22:50:23,453 [1-IconFactory-preload] INFO  VASSAL.tools.icon.IconFactory - Icon family calculator created for calculator.png
2015-11-17 22:50:23,453 [1-IconFactory-preload] INFO  VASSAL.tools.icon.IconFactory - Icon family go-up created for go-up.png
2015-11-17 22:50:23,453 [1-IconFactory-preload] INFO  VASSAL.tools.icon.IconFactory - Icon family VASSAL-jabber created for VASSAL-jabber.png
2015-11-17 22:50:23,453 [1-IconFactory-preload] INFO  VASSAL.tools.icon.IconFactory - Icon family jabber created for jabber.png
2015-11-17 22:50:23,453 [1-IconFactory-preload] INFO  VASSAL.tools.icon.IconFactory - Icon family bug created for bug.png
2015-11-17 22:50:23,453 [1-IconFactory-preload] INFO  VASSAL.tools.icon.IconFactory - Icon family yes created for yes.svg
2015-11-17 22:50:23,453 [1-IconFactory-preload] INFO  VASSAL.tools.icon.IconFactory - Icon family no created for no.svg
2015-11-17 22:50:25,008 [1-AWT-EventQueue-0] ERROR VASSAL.i18n.BundleHelper - No Translation: Icon when pieces and draggable overlays are showing:
2015-11-17 22:50:25,009 [1-AWT-EventQueue-0] ERROR VASSAL.i18n.BundleHelper - No Translation: Icon when only draggable overlays are showing:
2015-11-17 22:50:25,009 [1-AWT-EventQueue-0] ERROR VASSAL.i18n.BundleHelper - No Translation: Icon when only map is showing:
2015-11-17 22:50:25,900 [1-AWT-EventQueue-0] WARN  VASSAL.launch.BasicModule - VASL version 6.3.0
2015-11-17 22:50:25,922 [1-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Loading extension /Users/zgrose/Dropbox/VASSAL/VASL/extensions/4los.mdx
2015-11-17 22:50:25,927 [1-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Extension 4los v1.0 loaded 
2015-11-17 22:50:25,927 [1-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Loading extension /Users/zgrose/Dropbox/VASSAL/VASL/extensions/BFP.mdx
2015-11-17 22:50:25,954 [1-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Extension BFP v3.0 loaded 
2015-11-17 22:50:25,955 [1-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Loading extension /Users/zgrose/Dropbox/VASSAL/VASL/extensions/ChapterD.mdx
2015-11-17 22:50:25,958 [1-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Extension ChapterD v1.0 loaded 
2015-11-17 22:50:25,958 [1-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Loading extension /Users/zgrose/Dropbox/VASSAL/VASL/extensions/cloaking-display.vmdx
2015-11-17 22:50:25,969 [1-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Extension cloaking-display v0.0 loaded 
2015-11-17 22:50:25,969 [1-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Loading extension /Users/zgrose/Dropbox/VASSAL/VASL/extensions/FB.mdx
2015-11-17 22:50:25,978 [1-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Extension FB v1.1 - 13 May 2012 loaded 
2015-11-17 22:50:25,978 [1-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Loading extension /Users/zgrose/Dropbox/VASSAL/VASL/extensions/TerrainChart.mdx
2015-11-17 22:50:25,980 [1-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Extension TerrainChart v1.2.1 loaded 
2015-11-17 22:50:25,980 [1-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Loading extension /Users/zgrose/Dropbox/VASSAL/VASL/extensions/Tray.mdx
2015-11-17 22:50:25,984 [1-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Extension Tray v0.0 loaded 
2015-11-17 22:50:33,265 [1-AWT-EventQueue-0] INFO  VASSAL.tools.io.ProcessLauncher - launching /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -classpath Contents/Resources/Java/Vengine.jar -Xmx156M -DVASSAL.id=42 -Duser.home=/Users/zgrose -DVASSAL.port=64801 VASSAL.tools.image.tilecache.ZipFileImageTiler /Users/zgrose/Dropbox/VASSAL/VASL/boards/bd07 /Users/zgrose/Library/Application Support/VASSAL/tiles/9aac4cd020f3d2ea198637ab50d2d33da59aa522 256 256 bd07.gif
2015-11-17 22:50:33,654 [42-main] INFO  VASSAL.tools.image.tilecache.ZipFileImageTiler - Starting
2015-11-17 22:50:33,737 [42-main] INFO  VASSAL.tools.image.tilecache.FileArchiveImageTiler - Tiling bd07.gif
2015-11-17 22:50:34,057 [42-main] INFO  VASSAL.tools.image.tilecache.ZipFileImageTiler - Exiting
2015-11-17 22:50:39,842 [1-AWT-EventQueue-0] ERROR VASSAL.tools.ErrorDialog - 
java.lang.NullPointerException: null
	at sun.lwawt.macosx.CDragSourceContextPeer.startDrag(CDragSourceContextPeer.java:107) ~[na:1.8.0_66]
	at sun.awt.dnd.SunDragSourceContextPeer.startDrag(SunDragSourceContextPeer.java:135) ~[na:1.8.0_66]
	at sun.lwawt.macosx.CDragSourceContextPeer.startDrag(CDragSourceContextPeer.java:88) ~[na:1.8.0_66]
	at java.awt.dnd.DragSource.startDrag(DragSource.java:321) ~[na:1.8.0_66]
	at java.awt.dnd.DragSource.startDrag(DragSource.java:396) ~[na:1.8.0_66]
	at java.awt.dnd.DragGestureEvent.startDrag(DragGestureEvent.java:292) ~[na:1.8.0_66]
	at VASSAL.build.module.map.PieceMover$AbstractDragHandler.beginDragging(PieceMover.java:1226) ~[Vengine.jar:na]
	at VASSAL.build.module.map.PieceMover$AbstractDragHandler.dragGestureRecognized(PieceMover.java:1150) ~[Vengine.jar:na]
	at VASSAL.build.module.map.PieceMover$DragHandler.dragGestureRecognized(PieceMover.java:1380) ~[Vengine.jar:na]
	at VASL.build.module.map.QCMenuItem$1.dragGestureRecognized(QC.java:210) ~[na:na]
	at java.awt.dnd.DragGestureRecognizer.fireDragGestureRecognized(DragGestureRecognizer.java:361) ~[na:1.8.0_66]
	at sun.lwawt.macosx.CMouseDragGestureRecognizer.mouseDragged(CMouseDragGestureRecognizer.java:139) ~[na:1.8.0_66]
	at java.awt.AWTEventMulticaster.mouseDragged(AWTEventMulticaster.java:320) ~[na:1.8.0_66]
	at java.awt.Component.processMouseMotionEvent(Component.java:6583) ~[na:1.8.0_66]
	at javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3342) ~[na:1.8.0_66]
	at java.awt.Component.processEvent(Component.java:6304) ~[na:1.8.0_66]
	at java.awt.Container.processEvent(Container.java:2236) ~[na:1.8.0_66]
	at java.awt.Component.dispatchEventImpl(Component.java:4891) ~[na:1.8.0_66]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[na:1.8.0_66]
	at java.awt.Component.dispatchEvent(Component.java:4713) ~[na:1.8.0_66]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) ~[na:1.8.0_66]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4542) ~[na:1.8.0_66]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) ~[na:1.8.0_66]
	at java.awt.Container.dispatchEventImpl(Container.java:2280) ~[na:1.8.0_66]
	at java.awt.Window.dispatchEventImpl(Window.java:2750) ~[na:1.8.0_66]
	at java.awt.Component.dispatchEvent(Component.java:4713) ~[na:1.8.0_66]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[na:1.8.0_66]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_66]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[na:1.8.0_66]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[na:1.8.0_66]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_66]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.8.0_66]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[na:1.8.0_66]
	at java.awt.EventQueue$4.run(EventQueue.java:731) ~[na:1.8.0_66]
	at java.awt.EventQueue$4.run(EventQueue.java:729) ~[na:1.8.0_66]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_66]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.8.0_66]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[na:1.8.0_66]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_66]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_66]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_66]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_66]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_66]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_66]
2015-11-17 22:53:43,966 [1-AWT-EventQueue-0] INFO  VASSAL.build.GameModule - Exiting
2015-11-17 22:53:44,404 [0-IPC receiver for 1207869049] ERROR VASSAL.tools.ipc.IPCMessageReceiver - 
java.io.EOFException: null
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2608) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1319) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371) ~[na:1.8.0_66]
	at VASSAL.tools.ipc.IPCMessageReceiver.run(IPCMessageReceiver.java:34) ~[Vengine.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
2015-11-17 22:54:17,363 [0-SwingWorker-pool-714192875-thread-2] INFO  VASSAL.launch.AbstractLaunchAction - Loading module file /Users/zgrose/Dropbox/VASSAL/VASL/vasl-6.3.0.vmod
2015-11-17 22:54:17,571 [0-SwingWorker-pool-714192875-thread-2] INFO  VASSAL.launch.TilingHandler - No images to tile.
2015-11-17 22:54:17,572 [0-SwingWorker-pool-714192875-thread-2] INFO  VASSAL.launch.AbstractLaunchAction - Loading module VASL
2015-11-17 22:54:17,572 [0-SwingWorker-pool-714192875-thread-2] INFO  VASSAL.tools.io.ProcessLauncher - launching /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -Xms512M -Xmx1024M -DVASSAL.id=3 -DVASSAL.port=64989 -Duser.home=/Users/zgrose -Duser.dir=/Applications/VASSAL.app -cp Contents/Resources/Java/Vengine.jar -Xdock:name=VASL -Xdock:icon=/Applications/VASSAL.app/Contents/Resources/VASSAL.icns -Dapple.awt.graphics.UseQuartz=false VASSAL.launch.Player --load -- /Users/zgrose/Dropbox/VASSAL/VASL/vasl-6.3.0.vmod
2015-11-17 22:54:18,414 [3-main] INFO  VASSAL.launch.StartUp - Starting
2015-11-17 22:54:18,420 [3-main] INFO  VASSAL.launch.StartUp - OS Mac OS X 10.11.1
2015-11-17 22:54:18,420 [3-main] INFO  VASSAL.launch.StartUp - Java version 1.8.0_66
2015-11-17 22:54:18,420 [3-main] INFO  VASSAL.launch.StartUp - VASSAL version 3.2.15
2015-11-17 22:54:18,421 [3-main] INFO  VASSAL.launch.Launcher - Player
2015-11-17 22:54:19,573 [3-IconFactory-preload] INFO  VASSAL.tools.icon.IconFactory - VASSAL images folder found at jar:file:/Applications/VASSAL.app/Contents/Resources/Java/Vengine.jar!/images/
2015-11-17 22:54:19,575 [3-IconFactory-preload] INFO  VASSAL.tools.icon.IconFactory - Icon family network-server created for network-server.png
2015-11-17 22:54:19,576 [3-IconFactory-preload] INFO  VASSAL.tools.icon.IconFactory - Icon family go-down created for go-down.png
2015-11-17 22:54:19,576 [3-IconFactory-preload] INFO  VASSAL.tools.icon.IconFactory - Icon family network-idle created for network-idle.png
2015-11-17 22:54:19,576 [3-IconFactory-preload] INFO  VASSAL.tools.icon.IconFactory - Icon family VASSAL created for VASSAL.png
2015-11-17 22:54:19,576 [3-IconFactory-preload] INFO  VASSAL.tools.icon.IconFactory - Icon family calculator created for calculator.png
2015-11-17 22:54:19,576 [3-IconFactory-preload] INFO  VASSAL.tools.icon.IconFactory - Icon family go-up created for go-up.png
2015-11-17 22:54:19,576 [3-IconFactory-preload] INFO  VASSAL.tools.icon.IconFactory - Icon family VASSAL-jabber created for VASSAL-jabber.png
2015-11-17 22:54:19,576 [3-IconFactory-preload] INFO  VASSAL.tools.icon.IconFactory - Icon family jabber created for jabber.png
2015-11-17 22:54:19,576 [3-IconFactory-preload] INFO  VASSAL.tools.icon.IconFactory - Icon family bug created for bug.png
2015-11-17 22:54:19,576 [3-IconFactory-preload] INFO  VASSAL.tools.icon.IconFactory - Icon family yes created for yes.svg
2015-11-17 22:54:19,576 [3-IconFactory-preload] INFO  VASSAL.tools.icon.IconFactory - Icon family no created for no.svg
2015-11-17 22:54:20,530 [3-AWT-EventQueue-0] ERROR VASSAL.i18n.BundleHelper - No Translation: Icon when pieces and draggable overlays are showing:
2015-11-17 22:54:20,530 [3-AWT-EventQueue-0] ERROR VASSAL.i18n.BundleHelper - No Translation: Icon when only draggable overlays are showing:
2015-11-17 22:54:20,530 [3-AWT-EventQueue-0] ERROR VASSAL.i18n.BundleHelper - No Translation: Icon when only map is showing:
2015-11-17 22:54:21,410 [3-AWT-EventQueue-0] WARN  VASSAL.launch.BasicModule - VASL version 6.3.0
2015-11-17 22:54:21,429 [3-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Loading extension /Users/zgrose/Dropbox/VASSAL/VASL/extensions/4los.mdx
2015-11-17 22:54:21,434 [3-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Extension 4los v1.0 loaded 
2015-11-17 22:54:21,434 [3-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Loading extension /Users/zgrose/Dropbox/VASSAL/VASL/extensions/BFP.mdx
2015-11-17 22:54:21,461 [3-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Extension BFP v3.0 loaded 
2015-11-17 22:54:21,461 [3-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Loading extension /Users/zgrose/Dropbox/VASSAL/VASL/extensions/ChapterD.mdx
2015-11-17 22:54:21,463 [3-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Extension ChapterD v1.0 loaded 
2015-11-17 22:54:21,463 [3-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Loading extension /Users/zgrose/Dropbox/VASSAL/VASL/extensions/cloaking-display.vmdx
2015-11-17 22:54:21,474 [3-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Extension cloaking-display v0.0 loaded 
2015-11-17 22:54:21,474 [3-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Loading extension /Users/zgrose/Dropbox/VASSAL/VASL/extensions/FB.mdx
2015-11-17 22:54:21,483 [3-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Extension FB v1.1 - 13 May 2012 loaded 
2015-11-17 22:54:21,483 [3-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Loading extension /Users/zgrose/Dropbox/VASSAL/VASL/extensions/TerrainChart.mdx
2015-11-17 22:54:21,485 [3-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Extension TerrainChart v1.2.1 loaded 
2015-11-17 22:54:21,485 [3-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Loading extension /Users/zgrose/Dropbox/VASSAL/VASL/extensions/Tray.mdx
2015-11-17 22:54:21,488 [3-AWT-EventQueue-0] INFO  VASSAL.build.module.ExtensionsLoader - Extension Tray v0.0 loaded 
2015-11-17 22:54:32,611 [3-AWT-EventQueue-0] INFO  VASSAL.tools.io.ProcessLauncher - launching /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -classpath Contents/Resources/Java/Vengine.jar -Xmx156M -DVASSAL.id=42 -Duser.home=/Users/zgrose -DVASSAL.port=64995 VASSAL.tools.image.tilecache.ZipFileImageTiler /Users/zgrose/Dropbox/VASSAL/VASL/boards/bd01 /Users/zgrose/Library/Application Support/VASSAL/tiles/9aac4cd020f3d2ea198637ab50d2d33da59aa522 256 256 bd01.gif
2015-11-17 22:54:33,001 [42-main] INFO  VASSAL.tools.image.tilecache.ZipFileImageTiler - Starting
2015-11-17 22:54:33,087 [42-main] INFO  VASSAL.tools.image.tilecache.FileArchiveImageTiler - Tiling bd01.gif
2015-11-17 22:54:33,338 [42-main] INFO  VASSAL.tools.image.tilecache.ZipFileImageTiler - Exiting
2015-11-17 22:55:18,072 [3-AWT-EventQueue-0] ERROR VASSAL.tools.ErrorDialog - 
java.lang.NullPointerException: null
	at sun.lwawt.macosx.CDragSourceContextPeer.startDrag(CDragSourceContextPeer.java:107) ~[na:1.8.0_66]
	at sun.awt.dnd.SunDragSourceContextPeer.startDrag(SunDragSourceContextPeer.java:135) ~[na:1.8.0_66]
	at sun.lwawt.macosx.CDragSourceContextPeer.startDrag(CDragSourceContextPeer.java:88) ~[na:1.8.0_66]
	at java.awt.dnd.DragSource.startDrag(DragSource.java:321) ~[na:1.8.0_66]
	at java.awt.dnd.DragSource.startDrag(DragSource.java:396) ~[na:1.8.0_66]
	at java.awt.dnd.DragGestureEvent.startDrag(DragGestureEvent.java:292) ~[na:1.8.0_66]
	at VASSAL.build.module.map.PieceMover$AbstractDragHandler.beginDragging(PieceMover.java:1226) ~[Vengine.jar:na]
	at VASSAL.build.module.map.PieceMover$AbstractDragHandler.dragGestureRecognized(PieceMover.java:1150) ~[Vengine.jar:na]
	at VASSAL.build.module.map.PieceMover$DragHandler.dragGestureRecognized(PieceMover.java:1380) ~[Vengine.jar:na]
	at VASL.build.module.map.QCMenuItem$1.dragGestureRecognized(QC.java:210) ~[na:na]
	at java.awt.dnd.DragGestureRecognizer.fireDragGestureRecognized(DragGestureRecognizer.java:361) ~[na:1.8.0_66]
	at sun.lwawt.macosx.CMouseDragGestureRecognizer.mouseDragged(CMouseDragGestureRecognizer.java:139) ~[na:1.8.0_66]
	at java.awt.AWTEventMulticaster.mouseDragged(AWTEventMulticaster.java:320) ~[na:1.8.0_66]
	at java.awt.Component.processMouseMotionEvent(Component.java:6583) ~[na:1.8.0_66]
	at javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3342) ~[na:1.8.0_66]
	at java.awt.Component.processEvent(Component.java:6304) ~[na:1.8.0_66]
	at java.awt.Container.processEvent(Container.java:2236) ~[na:1.8.0_66]
	at java.awt.Component.dispatchEventImpl(Component.java:4891) ~[na:1.8.0_66]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[na:1.8.0_66]
	at java.awt.Component.dispatchEvent(Component.java:4713) ~[na:1.8.0_66]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) ~[na:1.8.0_66]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4542) ~[na:1.8.0_66]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) ~[na:1.8.0_66]
	at java.awt.Container.dispatchEventImpl(Container.java:2280) ~[na:1.8.0_66]
	at java.awt.Window.dispatchEventImpl(Window.java:2750) ~[na:1.8.0_66]
	at java.awt.Component.dispatchEvent(Component.java:4713) ~[na:1.8.0_66]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[na:1.8.0_66]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_66]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[na:1.8.0_66]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[na:1.8.0_66]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_66]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.8.0_66]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[na:1.8.0_66]
	at java.awt.EventQueue$4.run(EventQueue.java:731) ~[na:1.8.0_66]
	at java.awt.EventQueue$4.run(EventQueue.java:729) ~[na:1.8.0_66]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_66]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.8.0_66]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[na:1.8.0_66]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_66]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_66]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_66]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_66]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_66]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_66]

**Comment by zgrose** [comment]
Also mentioned on Facebook and GameSquad.

**Comment by davidsullivan317** [comment]
No idea really what's going on here. The only change to QC.java was to slide the move button to the left. It appears to be a Mac issue. Any chance you could try 6.3 with a different JRE? My Mac died.

**Comment by uckelman** [comment]
This likely to be a bug in the Mac JRE in use.

**Comment by Taschenschieber** [comment]
Not true, there was also this change: https://github.com/vasl-developers/vasl/commit/860a755f74cc3a6b5c28f0ac6666df9aaa38fbaa

Does not really look like it would cause something like this, though?

**Comment by FredKors** [comment]
I'll check it this evening but I have only a Mac virtual machine...

----- Messaggio originale -----
Da: "David Sullivan" <notifications@github.com>
Inviato: ‎18/‎11/‎2015 08:49
A: "vasl-developers/vasl" <vasl@noreply.github.com>
Oggetto: Re: [vasl] Dragging a counter off a QC menu throws NPE (#251)

No idea really what's going on here. The only change to QC.java was to slide the move button to the left. It appears to be a Mac issue. Any chance you could try 6.3 with a different JRE? My Mac died.

**Comment by FredKors** [comment]
I think it's ok now. Please check! :-)

**Comment by davidsullivan317** [comment]
I've put a build out for testing.

**Comment by zgrose** [comment]
build 20151118 passes this test.
