### ISSUE TITLE
NPE when opponent checks LOS

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#469]
Getting the following when my opponent checks LOS:

2018-03-01 19:42:54,963 [6-AWT-EventQueue-0] ERROR VASSAL.tools.ErrorDialog - 
java.lang.NullPointerException: null
	at VASL.build.module.map.VASLThread.setSourceandTargetLevels(VASLThread.java:1009) ~[na:na]
	at VASL.build.module.map.VASLThread.setEndPointsandLevels(VASLThread.java:998) ~[na:na]
	at VASL.build.module.map.VASLThread$VASLLOSCommand.executeCommand(VASLThread.java:1132) ~[na:na]
	at VASSAL.command.Command.execute(Command.java:54) ~[Vengine.jar:na]
	at VASSAL.chat.CommandDecoder$1.run(CommandDecoder.java:40) [Vengine.jar:na]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) [na:1.7.0_67]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [na:1.7.0_67]
	at java.awt.EventQueue.access$200(Unknown Source) [na:1.7.0_67]
	at java.awt.EventQueue$3.run(Unknown Source) [na:1.7.0_67]
	at java.awt.EventQueue$3.run(Unknown Source) [na:1.7.0_67]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.7.0_67]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source) [na:1.7.0_67]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [na:1.7.0_67]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [na:1.7.0_67]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [na:1.7.0_67]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [na:1.7.0_67]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.7.0_67]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.7.0_67]
	at java.awt.EventDispatchThread.run(Unknown Source) [na:1.7.0_67]

**Comment by derimmer** [comment]
Versions being used? This was fixed (at least I thought so) in 6.4.0. But if your opponent was using an earlier version this error could result.

Can you trap the values of the parameters being passed into .setSourceandTargetLevels?

Which line in .setSourceAndTargetLevels() triggers the error? I have made changes elsewhere in VASLThread and line numbers no longer correspond.

**Comment by davidsullivan317** [comment]
Let me check with Ted and see what version he is on.

**Comment by davidsullivan317** [comment]
Ted is on 6.4.1. You can find the line number by looking at the version of the file in the 6.4.1 branch. https://github.com/vasl-developers/vasl/blob/release-6.4.1/src/VASL/build/module/map/VASLThread.java 

this is the offending line: if (source.getName().contains("Rooftop")) {

It looks like it occurs if the source location is null when executeCommand runs.

**Comment by derimmer** [comment]
OK. I shall move to debug this.

**Comment by derimmer** [comment]
Sully, can't replicate the error. Can you give me more context - bd number? Hexes? What was Ted trying to do - string a plain los or actually change the source or target level up or down? Thanks.

**Comment by derimmer** [comment]
Think I have this fixed and will include fix in 6.4.2
